# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('node', models.CharField(max_length=32)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
