# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('prediction', models.FloatField(blank=True, null=True)),
                ('is_ideal_charge', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='iso.Node')),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('start', 'node')]),
        ),
    ]
