# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_auto_20180424_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='in_range',
            field=models.BooleanField(default=False),
        ),
    ]
